baseURL = "https://liubeike.com/blog/"
languageCode = "zh-CN"
title = "Baker的个人博客"
theme = "hugo-PaperMod"
[params.homeInfoParams]
Title = "求知若渴，虚怀若谷。"
Content = "对本博客内容有任何疑问，欢迎反馈邮箱：liubeike99@gmail.com"